# GET ALL USERS
GET  http://localhost:5000/users/
###

# GET A SINGLE USER
GET  http://localhost:5000/users/2
###

# REGISTER A USER
POST  http://localhost:5000/register 
Content-Type: application/json

{
    "email": "patient@mail",
    "password": "123456"
}
###

# SIGN IN
POST  http://localhost:5000/login 
Content-Type: application/json

{
    "email": "patient@mail",
    "password": "123456"
}
###

# GET ALL BOOKINGS
http://localhost:5000/bookings/

###

# GET ALL BOOKINGS FOR A USER
http://localhost:5000/users/1/bookings

###
http://localhost:5000/listings/

###

# POST http://localhost:5000/posts
# Content-Type: application/json

# {
#     "title": "airbnb clone",
#     "airbnb": "dineo"
# }